#!/bin/bash

# Test the new hierarchical TUI with diff view mode switching
echo "Testing hierarchical TUI with diff view mode switching..."
echo ""
echo "Instructions:"
echo "1. Run: ./target/release/ai-commit --tui"
echo "2. Navigate to Branches or Tags"
echo "3. Press Enter to view commits"
echo "4. Press Enter on a commit to view diff"
echo "5. In diff view, test these keys:"
echo "   - Press '1' for Unified view"
echo "   - Press '2' for Side-by-Side view (default)"
echo "   - Press '3' for Split view"
echo "   - Press 'v' to cycle through views"
echo "   - Press 't' to toggle file list"
echo "   - Press 'j'/'k' to navigate files"
echo "   - Press 'J'/'K' to scroll diff content"
echo "   - Press 'ESC' or 'q' to go back"
echo ""
echo "The view mode should now switch correctly when pressing 1, 2, or 3!"