/// Markdown 摘要模板
pub const MARKDOWN_SUMMARY_TEMPLATE: &str = r#"# 📋 Code Review Report

## 📊 Project Summary

| Metric | Value |
|--------|-------|
| **Project** | `{{summary.project_path}}` |
| **Files Analyzed** | {{summary.files_analyzed}} |
| **Languages** | {{#each summary.languages_detected}}{{this}}{{#unless @last}}, {{/unless}}{{/each}} |
| **Analysis Duration** | {{format_duration summary.analysis_duration}} |
| **Overall Score** | **{{overall_score}}/10** ⭐ |
| **Generated** | {{summary.created_at}} |

## 🎯 Issue Distribution

```
Critical: {{summary.critical_issues}} 🔴
High:     {{summary.high_issues}} 🟠
Medium:   {{summary.medium_issues}} 🟡
Low:      {{summary.low_issues}} 🔵
Total:    {{summary.total_issues}}
```

### Quality Score Breakdown
{{progress_bar overall_score 20}} {{overall_score}}/10

{{#if recommendations}}
## 💡 Key Recommendations

{{#each recommendations}}
- ✅ {{this}}
{{/each}}
{{/if}}

---
"#;

/// Markdown 问题列表模板
pub const MARKDOWN_ISSUES_TEMPLATE: &str = r#"
{{#if static_analysis_results}}
## 🔍 Static Analysis Results

{{#each static_analysis_results}}
### 🛠️ {{tool_name}} Analysis

**File**: `{{file_path}}`

{{#if issues}}
| Severity | Line | Issue | Suggestion |
|----------|------|-------|------------|
{{#each issues}}
| {{severity_emoji severity}} {{severity}} | {{line_number}} | {{message}} | {{#if suggestion}}{{suggestion}}{{else}}-{{/if}} |
{{/each}}
{{else}}
✅ No issues found
{{/if}}

{{/each}}
{{/if}}

{{#if ai_review_results}}
## 🤖 AI-Powered Code Review

{{#each ai_review_results}}
### 📁 `{{file_path}}`

<details>
<summary><strong>{{provider}} Analysis</strong> - Quality Score: <strong>{{quality_score}}/10</strong></summary>

{{#if suggestions}}
#### 💡 Improvement Suggestions

{{#each suggestions}}
- 🔧 {{this}}
{{/each}}
{{/if}}

{{#if learning_resources}}
#### 📚 Learning Resources

{{#each learning_resources}}
- 📖 [{{this}}]({{this}})
{{/each}}
{{/if}}

</details>

{{/each}}
{{/if}}

{{#if sensitive_info_results}}
## 🔒 Security & Sensitive Information

> ⚠️ **Warning**: Potential sensitive information detected in your codebase

{{#each sensitive_info_results}}
### 📄 `{{file_path}}`

{{#each items}}
<div class="alert alert-{{#if (eq risk_level "Critical")}}danger{{else}}{{#if (eq risk_level "High")}}warning{{else}}info{{/if}}{{/if}}">

**{{info_type}}** detected at line **{{line_number}}**

- **Risk Level**: {{risk_level_emoji risk_level}} {{risk_level}}
- **Confidence**: {{format_percentage confidence}}
- **Preview**: `{{masked_text}}`

{{#if recommendations}}
**Recommended Actions**:
{{#each recommendations}}
- 🛡️ {{this}}
{{/each}}
{{/if}}

</div>

{{/each}}

{{/each}}
{{/if}}

{{#if complexity_results}}
## 📊 Code Complexity Analysis

{{#each complexity_results}}
### 📁 `{{file_path}}`

#### Overall Metrics
```
Average Cyclomatic Complexity: {{overall_metrics.average_cyclomatic}}
Average Cognitive Complexity:  {{overall_metrics.average_cognitive}}
Functions Over Threshold:      {{overall_metrics.functions_over_threshold}}
```

{{#if hotspots}}
#### 🔥 Complexity Hotspots

| Function | Line | Complexity Score | Status |
|----------|------|------------------|--------|
{{#each hotspots}}
| `{{function_name}}` | {{line_number}} | {{complexity_score}} | {{#if (gt complexity_score 10)}}🔴 High{{else}}{{#if (gt complexity_score 5)}}🟡 Medium{{else}}🟢 Low{{/if}}{{/if}} |
{{/each}}
{{/if}}

{{/each}}
{{/if}}

{{#if duplication_results}}
## 🔄 Code Duplication Analysis

{{#each duplication_results}}
### 📁 `{{file_path}}`

**Duplication Rate**: {{format_percentage duplication_percentage}}

{{#if duplications}}
#### Detected Duplications

{{#each duplications}}
<details>
<summary><strong>{{duplication_type}} Duplication</strong> - {{lines_count}} lines ({{format_percentage similarity_score}} similarity)</summary>

**Source**: `{{source_location.file_path}}:{{source_location.line_start}}-{{source_location.line_end}}`

**Also found in**:
{{#each target_locations}}
- `{{file_path}}:{{line_start}}-{{line_end}}`
{{/each}}

</details>
{{/each}}
{{/if}}

{{/each}}
{{/if}}
"#;

/// Markdown 统计信息模板
pub const MARKDOWN_STATISTICS_TEMPLATE: &str = r#"
## 📈 Statistics

### Analysis Coverage
{{progress_bar 0.85 30}} 85% Complete

### Quality Metrics
- **Code Quality**: {{progress_bar overall_score 20}} {{overall_score}}/10
- **Security Score**: {{progress_bar 0.9 20}} 9.0/10
- **Maintainability**: {{progress_bar 0.75 20}} 7.5/10

### Performance
- **Analysis Time**: {{format_duration metadata.analysis_duration}}
- **Files per Second**: {{files_per_second}}
- **Memory Usage**: {{memory_usage}}

---
*Generated by AI-Commit v{{metadata.version}}*
"#;

/// JSON 完整模板
pub const JSON_FULL_TEMPLATE: &str = r#"{
  "summary": {
    "project_path": "{{summary.project_path}}",
    "files_analyzed": {{summary.files_analyzed}},
    "languages_detected": [{{#each summary.languages_detected}}"{{this}}"{{#unless @last}},{{/unless}}{{/each}}],
    "total_issues": {{summary.total_issues}},
    "critical_issues": {{summary.critical_issues}},
    "high_issues": {{summary.high_issues}},
    "medium_issues": {{summary.medium_issues}},
    "low_issues": {{summary.low_issues}},
    "analysis_duration": {{summary.analysis_duration}},
    "created_at": "{{summary.created_at}}"
  },
  "overall_score": {{overall_score}},
  "static_analysis_results": [
    {{#each static_analysis_results}}
    {
      "tool_name": "{{tool_name}}",
      "file_path": "{{file_path}}",
      "issues": [
        {{#each issues}}
        {
          "severity": "{{severity}}",
          "message": "{{message}}",
          "line_number": {{line_number}},
          "suggestion": "{{suggestion}}"
        }{{#unless @last}},{{/unless}}
        {{/each}}
      ]
    }{{#unless @last}},{{/unless}}
    {{/each}}
  ],
  "recommendations": [{{#each recommendations}}"{{this}}"{{#unless @last}},{{/unless}}{{/each}}],
  "metadata": {
    "version": "{{metadata.version}}",
    "generated_at": "{{metadata.generated_at}}"
  }
}"#;

/// Text 摘要模板
pub const TEXT_SUMMARY_TEMPLATE: &str = r#"
================================================================================
                            CODE REVIEW REPORT
================================================================================

Project: {{summary.project_path}}
Files Analyzed: {{summary.files_analyzed}}
Languages: {{#each summary.languages_detected}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}
Analysis Duration: {{format_duration summary.analysis_duration}}
Overall Score: {{overall_score}}/10
Generated: {{summary.created_at}}

ISSUE SUMMARY
-------------
Critical: {{summary.critical_issues}}
High:     {{summary.high_issues}}
Medium:   {{summary.medium_issues}}
Low:      {{summary.low_issues}}
Total:    {{summary.total_issues}}

{{#if recommendations}}
KEY RECOMMENDATIONS
-------------------
{{#each recommendations}}
• {{this}}
{{/each}}
{{/if}}

================================================================================
"#;

/// Text 问题列表模板
pub const TEXT_ISSUES_TEMPLATE: &str = r#"
{{#if static_analysis_results}}
STATIC ANALYSIS RESULTS
=======================

{{#each static_analysis_results}}
{{tool_name}} - {{file_path}}
{{repeat "-" 50}}

{{#each issues}}
[{{severity}}] Line {{line_number}}: {{message}}
{{#if suggestion}}
   Suggestion: {{suggestion}}
{{/if}}

{{/each}}
{{/each}}
{{/if}}

{{#if ai_review_results}}
AI REVIEW RESULTS
=================

{{#each ai_review_results}}
{{file_path}} ({{provider}})
{{repeat "-" 50}}

Quality Score: {{quality_score}}/10

{{#if suggestions}}
Suggestions:
{{#each suggestions}}
• {{this}}
{{/each}}
{{/if}}

{{#if learning_resources}}
Learning Resources:
{{#each learning_resources}}
• {{this}}
{{/each}}
{{/if}}

{{/each}}
{{/if}}

{{#if sensitive_info_results}}
SENSITIVE INFORMATION DETECTION
===============================

{{#each sensitive_info_results}}
{{file_path}}
{{repeat "-" 50}}

{{#each items}}
[{{risk_level}}] {{info_type}} at line {{line_number}}
Confidence: {{format_percentage confidence}}
Masked: {{masked_text}}
{{#if recommendations}}
Recommendations:
{{#each recommendations}}
• {{this}}
{{/each}}
{{/if}}

{{/each}}
{{/each}}
{{/if}}
"#;