name: Release Binaries

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write  # 需要这个权限来创建 releases 和上传文件

jobs:
  release:
    name: release ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
            os: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            archive: zip
            os: macos-latest
          - target: aarch64-apple-darwin
            archive: zip
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Install MinGW for Windows cross-compilation
        if: matrix.target == 'x86_64-pc-windows-gnu' && runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Install musl and OpenSSL for Linux cross-compilation
        if: matrix.target == 'x86_64-unknown-linux-musl' && runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools musl-dev libssl-dev pkg-config

      - name: Set OpenSSL static env
        if: matrix.target == 'x86_64-unknown-linux-musl' && runner.os == 'Linux'
        run: echo "OPENSSL_STATIC=1" >> $GITHUB_ENV
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      
      - name: Build release binary
        run: |
          cargo build --release --target ${{ matrix.target }}
      
      - name: Create release archive
        run: |
          cd target/${{ matrix.target }}/release
          if [[ "${{ matrix.archive }}" == *"zip"* ]]; then
            zip -r ../../../../ai-commit-${{ matrix.target }}.zip ai-commit*
          fi
          if [[ "${{ matrix.archive }}" == *"tar.gz"* ]]; then
            tar -czf ../../../../ai-commit-${{ matrix.target }}.tar.gz ai-commit*
          fi
          if [[ "${{ matrix.archive }}" == *"tar.xz"* ]]; then
            tar -cJf ../../../../ai-commit-${{ matrix.target }}.tar.xz ai-commit*
          fi
          if [[ "${{ matrix.archive }}" == *"tar.zst"* ]]; then
            tar --zstd -cf ../../../../ai-commit-${{ matrix.target }}.tar.zst ai-commit*
          fi
      
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ai-commit-${{ matrix.target }}.zip
            ai-commit-${{ matrix.target }}.tar.gz
            ai-commit-${{ matrix.target }}.tar.xz
            ai-commit-${{ matrix.target }}.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
